/**
 * Power-user export formats — I1, I2, I3.
 *
 * - I1 JSON export of transactions (the backup format unencrypted)
 * - I2 Markdown monthly report
 * - I3 Read-only image share (covered by share-image.ts in Phase 7D)
 */
import type { TransactionWithJoins } from '@/db/queries/transactions';
import { formatINR, paiseToRupees } from './money';
import { formatDate } from './date';

export function transactionsToJson(items: TransactionWithJoins[]): string {
  return JSON.stringify(
    items.map((it) => ({
      id: it.id,
      occurredAt: it.occurredAt,
      type: it.type,
      amountInr: paiseToRupees(it.amountPaise),
      category: it.category?.name ?? null,
      account: it.account?.name ?? null,
      toAccount: it.toAccount?.name ?? null,
      payee: it.payee,
      note: it.note,
      source: it.source,
    })),
    null,
    2,
  );
}

export function monthlyReportMarkdown(opts: {
  monthLabel: string;
  spentPaise: number;
  incomePaise: number;
  topCategories: { name: string; total: number }[];
  topPayees: { payee: string; total: number }[];
}): string {
  const lines: string[] = [];
  lines.push(`# ${opts.monthLabel}`);
  lines.push('');
  lines.push(`- **Spent:** ${formatINR(opts.spentPaise)}`);
  lines.push(`- **Income:** ${formatINR(opts.incomePaise)}`);
  lines.push(`- **Net:** ${formatINR(opts.incomePaise - opts.spentPaise)}`);
  lines.push('');
  lines.push('## Top categories');
  for (const c of opts.topCategories) {
    lines.push(`- ${c.name} — ${formatINR(c.total)}`);
  }
  lines.push('');
  lines.push('## Top payees');
  for (const p of opts.topPayees) {
    lines.push(`- ${p.payee} — ${formatINR(p.total)}`);
  }
  lines.push('');
  lines.push(`_Generated by moneyNest on ${formatDate(new Date().toISOString(), 'YYYY-MM-DD')}_`);
  return lines.join('\n');
}
