/**
 * HRA rent receipt generator — C14.
 *
 * Generates a printable HTML "rent receipt" that can be saved/shared.
 * PDF rendering is left to the OS share dialog (most printers / Drive
 * targets accept HTML and render to PDF).
 */
import { formatINR } from './money';

export type RentReceipt = {
  tenantName: string;
  landlordName: string;
  landlordPan?: string;
  propertyAddress: string;
  amountPaise: number;
  fromIsoDate: string;
  toIsoDate: string;
  receiptNumber: string;
};

export function renderRentReceiptHtml(r: RentReceipt): string {
  return `<!doctype html><html><head><meta charset="utf-8"/><title>Rent receipt</title>
<style>
  body { font: 14px/1.5 system-ui, sans-serif; padding: 32px; color: #0F172A; }
  h1 { font-size: 22px; }
  .box { border: 1px solid #CBD5E1; border-radius: 12px; padding: 20px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  td, th { padding: 8px; border-bottom: 1px solid #E2E8F0; text-align: left; }
  .total { font-size: 20px; font-weight: 700; }
</style></head><body>
  <h1>Rent receipt #${r.receiptNumber}</h1>
  <div class="box">
    <table>
      <tr><th>Tenant</th><td>${r.tenantName}</td></tr>
      <tr><th>Landlord</th><td>${r.landlordName}${r.landlordPan ? ` (PAN: ${r.landlordPan})` : ''}</td></tr>
      <tr><th>Property</th><td>${r.propertyAddress}</td></tr>
      <tr><th>Period</th><td>${r.fromIsoDate.slice(0, 10)} to ${r.toIsoDate.slice(0, 10)}</td></tr>
      <tr><th>Amount</th><td class="total">${formatINR(r.amountPaise)}</td></tr>
    </table>
  </div>
  <p style="margin-top: 32px; color: #64748B;">
    Generated by moneyNest for HRA proof of payment.
  </p>
</body></html>`;
}
