export const common = {
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  done: 'Done',
  back: 'Back',
  next: 'Next',
  retry: 'Retry',
  yes: 'Yes',
  no: 'No',
  loading: 'Loading…',
  add: 'Add',
  search: 'Search',
  close: 'Close',
  confirm: 'Confirm',
  remove: 'Remove',
  undo: 'Undo',
  okay: 'Okay',
  continue: 'Continue',
  skip: 'Skip',
} as const;
