export const settings = {
  title: 'Settings',
  appearance: 'Appearance',
  theme: 'Theme',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  glassEnabled: 'Liquid Glass',
  glassEnabledBody: 'Translucent surfaces on supported devices.',
  privacy: 'Privacy',
  lock: 'App lock',
  lockBody: 'Require biometrics to open.',
  analytics: 'Anonymous usage',
  analyticsBody: 'Help improve the app (off by default).',
  crashes: 'Crash reports',
  crashesBody: 'Send anonymized crash reports (off by default).',
  backup: 'Backup',
  exportData: 'Export encrypted backup',
  importData: 'Restore from backup',
  changePassphrase: 'Change passphrase',
  about: 'About',
  version: 'Version',
  privacyPolicy: 'Privacy policy',
  support: 'Email support',
  deleteAllData: 'Delete all my data',
  deleteAllDataBody: 'Permanently erase everything. Cannot be undone.',
} as const;
