export const transactions = {
  title: 'Transactions',
  newTitle: 'Add transaction',
  editTitle: 'Edit transaction',
  expense: 'Expense',
  income: 'Income',
  transfer: 'Transfer',
  amount: 'Amount',
  category: 'Category',
  account: 'Account',
  toAccount: 'To account',
  date: 'Date',
  note: 'Note (optional)',
  payee: 'Payee (optional)',
  payeePlaceholder: 'e.g. Swiggy, Big Bazaar',
  notePlaceholder: 'A short note',
  pickCategory: 'Pick category',
  pickAccount: 'Pick account',
  saveTransaction: 'Save',
  deleteConfirm: 'Delete this transaction?',
  deletedToast: 'Transaction deleted',
  savedToast: 'Saved',
  searchPlaceholder: 'Search by note, payee, amount',
  emptyTitle: 'No transactions yet',
  emptyBody: 'Tap the mic or the + button to add your first one.',
} as const;
