export const common = {
  save: 'सेव करें',
  cancel: 'रद्द',
  delete: 'हटाएँ',
  edit: 'बदलें',
  done: 'हो गया',
  back: 'वापस',
  next: 'आगे',
  retry: 'फिर से',
  yes: 'हाँ',
  no: 'नहीं',
  loading: 'लोड हो रहा है…',
  add: 'जोड़ें',
  search: 'खोजें',
  close: 'बंद करें',
  confirm: 'पक्का',
  remove: 'हटाएँ',
  undo: 'पहले जैसा',
  okay: 'ठीक है',
  continue: 'जारी रखें',
  skip: 'छोड़ें',
} as const;
